version: 2.1

orbs:
  python: circleci/python@2.1.1
  coverage-reporter: codacy/coverage-reporter@13.15.0

jobs:
  testing-and-generating-report:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: mkdir test-results
          name: create directory for tests reports
      - run:
          command: |
            poetry run pytest --junitxml=test-results/junit.xml --cov-report xml:coverage.xml --cov=app tests/
          name: Generate test report
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: .
          paths:
            - coverage.xml
  codacy-coverage-report:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: .
      - coverage-reporter/send_report:
          coverage-reports: coverage.xml
          project-token: $CODACY_PROJECT_TOKEN

workflows:
  testing:
    jobs:
      - testing-and-generating-report
      - codacy-coverage-report:
          requires:
            - testing-and-generating-report
