version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@13.15.0
  aws-cli: circleci/aws-cli@4.1.2
  aws-ecr: circleci/aws-ecr@9.0.2
  aws-ecs: circleci/aws-ecs@4.0.0
jobs:
  testing-and-generating-report:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-testing-{{ checksum "poetry.lock" }}
      - run:
          name: install packages
          command: |
            poetry install --no-root --with test
      - run:
          name: create directory for tests reports
          command: mkdir test-results
      - run:
          name: Generate test report
          command: |
            poetry run pytest --junitxml=test-results/junit.xml --cov-report xml:coverage.xml --cov=app tests/
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: .
          paths:
            - coverage.xml
      - save_cache:
          key: v1-testing-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
  setup:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-linting-{{ checksum "poetry.lock" }}
      - run:
          name: Install packages
          command: |
            poetry install --no-root --only linting
      - persist_to_workspace:
          root: .
          paths:
            - "app"
            - "tests"
            - "pyproject.toml"
            - "poetry.lock"
      - save_cache:
          key: v1-linting-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
  linting-ruff:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-linting-{{ checksum "poetry.lock" }}
      - run:
          name: Install packages
          command: |
            poetry install --no-root --only linting
      - run:
          name: ruff linting
          command: |
            poetry run ruff --fix
      - run:
          name: ruff formatting
          command: |
            poetry run ruff format
      - save_cache:
          key: v1-linting-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
  linting-bandit:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-linting-{{ checksum "poetry.lock" }}
      - run:
          name: Install packages
          command: |
            poetry install --no-root --only linting
      - run:
          name: security linting with bandit
          command: |
            poetry run bandit -c pyproject.toml -r app/
      - save_cache:
          key: v1-linting-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
  linting-mypy:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-linting-{{ checksum "poetry.lock" }}
      - run:
          name: Install packages
          command: |
            poetry install --no-root --with linting
      - run:
          name: mypy type checking
          command: |
            poetry run mypy -p app
      - save_cache:
          key: v1-linting-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
  linting-pytype:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-linting-{{ checksum "poetry.lock" }}
      - run:
          name: Install packages
          command: |
            poetry install --no-root --with linting
      - run:
          name: pytype type checking
          command: |
            poetry run pytype
      - save_cache:
          key: v1-linting-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
  codacy-coverage-report:
    docker:
      - image: circleci/openjdk:8-jdk
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - coverage-reporter/send_report:
          coverage-reports: coverage.xml
          project-token: $CODACY_PROJECT_TOKEN

workflows:
  testing:
    jobs:
      - setup
      - linting-ruff:
          requires:
            - setup
      - linting-bandit:
          requires:
            - setup
      - linting-mypy:
          requires:
            - setup
      - linting-pytype:
          requires:
            - setup
      - testing-and-generating-report:
          requires:
            - linting-ruff
            - linting-bandit
            - linting-mypy
            - linting-pytype
      - codacy-coverage-report:
          requires:
            - testing-and-generating-report
      - aws-ecr/build_and_push_image:
          requires:
            - testing-and-generating-report
          auth:
            - aws-cli/setup:
                role_arn: ${AWS_ROLE_ARN}
          public_registry: true
          create_repo: true
          repo: ${MY_APP_PREFIX}
