version: 2.1

orbs:
  python: circleci/python@2.1.1
  coverage-reporter: codacy/coverage-reporter@13.15.0

jobs:
  testing-and-generating-report:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          args: "--with test"
          pkg-manager: poetry
      - run:
          command: mkdir test-results
          name: create directory for tests reports
      - run:
          command: |
            poetry run pytest --junitxml=test-results/junit.xml --cov-report xml:coverage.xml --cov=app tests/
          name: Generate test report
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: .
          paths:
            - coverage.xml
  setup:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          args: "--only linting"
          pkg-manager: poetry
      - persist_to_workspace:
          root: .
          paths:
            - "app"
            - "tests"
            - "pyproject.toml"
  linting-ruff:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run:
          name: ruff linting
          command: |
            ruff --fix
      - run:
          name: ruff formatting
          command: |
            ruff format
  linting-bandit:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run:
          name: security linting with bandit
          command: |
            bandit -c pyproject.toml -r app/
  linting-mypy:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run:
          name: mypy type checking
          command: |
            mypy -p app
  linting-pytype:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run:
          name: pytype type checking
          command: |
            pytype
  codacy-coverage-report:
    docker:
      - image: circleci/openjdk:8-jdk
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - coverage-reporter/send_report:
          coverage-reports: coverage.xml
          project-token: $CODACY_PROJECT_TOKEN

workflows:
  testing:
    jobs:
      - setup
      - linting-ruff:
          requires:
            - setup
      - linting-bandit:
          requires:
            - setup
      - linting-mypy:
          requires:
            - setup
      - linting-pytype:
          requires:
            - setup
      - testing-and-generating-report:
          requires:
            - linting-ruff
            - linting-bandit
            - linting-mypy
            - linting-pytype
      - codacy-coverage-report:
          requires:
            - testing-and-generating-report
